### ISSUE TITLE
error build ffmpeg for android ndk r16

### ISSUE THREAD

**Issue by manang** [wang-bin/avbuild#11]
Hi,
it is impossible to build ffmpeg for android with ndk r16.
the error is the following:
fatal error: jni.h: No such file or directory
 #include <jni.h>

with r15c it is possible.
Thanks

**Comment by wang-bin** [comment]
yes, the latest ndk is used for ci on linux. what's your platform? windows, linux or mac?

**Comment by wang-bin** [comment]
packages built by ci https://sourceforge.net/projects/avbuild/files

**Comment by manang** [comment]
I try with a fresh installation on a container ubuntu linux 16.04.
with mac I have the same issue.
which environment variables do you set to build ffmpeg?
I'm setting only FFSRC and ANDROID_NDK
Thank you very much

**Comment by wang-bin** [comment]
I build on macOS, 14.04 for every commit, using the latest ndk(now it's r16), sometimes build on windows. any ndk version should be fine.

build log: https://travis-ci.org/wang-bin/avbuild/jobs/336434155  https://travis-ci.org/wang-bin/avbuild/jobs/336434156

**Comment by wang-bin** [comment]
please show me more error messages

**Comment by manang** [comment]
Ok, I tried to build the release/3.3 branch.
the master branch is compiled.
Thank you very much
Angelo
