### ISSUE TITLE
Android prebuilt包在6.0后无法使用

### ISSUE THREAD

**Issue by QShen3** [wang-bin/avbuild#12]
谷歌在Android 6.0也就是Api level 23之后改变了使用外部库的安全策略，所以使用23之后的SDK编译的话无法继续使用提供的prebuilt包

[https://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-runtime](https://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-runtime)

**Comment by wang-bin** [comment]
具体什么问题？ffmpeg没调用非ndk的外部库，不存在这个问题，而且我自己和公司都用这脚本都好好的

**Comment by wang-bin** [comment]
这个要改ffmpeg汇编代码，你要给ffmpeg报bug。貌似只有x86有者问题

**Comment by alexeyvasilyev** [comment]
The issue can be fixed by adding --disable-asm for x86 build for Android.

   ...
  if [ -z "${ANDROID_ARCH/*86/}" ]; then
   ...
# Fix for https://trac.ffmpeg.org/ticket/4928
    USER_OPT+=" --disable-asm"
   ...
  elif [ -z "${ANDROID_ARCH/*arm*/}" ]; then
   ...
