### ISSUE TITLE
Issue Adding FFmpeg to Android Studio

### ISSUE THREAD

**Issue by mdemarco1234** [wang-bin/avbuild#16]
Hello,

 I added the prebuilt package to my Android project and I got this error below. I placed the file in the jnilib directory also in other places but it is not picking it up. Below I am sending you my gradle file. Do you know what the issue may be?

CANNOT LINK EXECUTABLE "/data/user/0/com.github.hiteshsondhi88.sampleffmpeg/files/ffmpeg": library "libavdevice.so" not found

apply plugin: 'com.android.library'
apply plugin: 'com.github.dcendents.android-maven'
apply plugin: "com.jfrog.bintray"

// This is the library version used when deploying the artifact
version = VERSION_NAME

android {
    compileSdkVersion 28
    buildToolsVersion rootProject.ext.buildToolsVersion as String
    defaultConfig {
        minSdkVersion 19
        targetSdkVersion 28
        versionName rootProject.ext.versionName as String
    }
    sourceSets.main {
        assets.srcDirs = ['assets']
        jni.srcDirs = [] //disable automatic ndk-build
        jniLibs.srcDirs = ['libs']
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    buildToolsVersion '27.0.3'
    productFlavors {
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile 'com.squareup.assertj:assertj-android:1.0.0'
    implementation 'com.android.support:appcompat-v7:28.0.0-rc01'
    implementation 'com.android.support.constraint:constraint-layout:2.0.0-alpha1'
    implementation 'com.android.support:design:28.0.0-rc01'
    implementation 'com.android.support.test:runner:1.0.2'
    implementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.android.support:design:28.0.0-rc01'
}

group = GROUP

install {
    repositories.mavenInstaller {
        // This generates POM.xml with proper parameters
        pom {
            project {
                packaging POM_PACKAGING

                // Add your description here
                name 'FFmpeg Android'
                description = POM_DESCRIPTION
                url POM_URL

                // Set your license
                licenses {
                    license {
                        name POM_LICENCE_NAME
                        url POM_LICENCE_URL
                    }
                }
                developers {
                    developer {
                        id POM_DEVELOPER_ID
                        name POM_DEVELOPER_NAME
                        email 'hitesh@writingminds.com'
                    }
                }
                scm {
                    connection POM_SCM_URL
                    developerConnection POM_SCM_URL
                    url POM_URL

                }
            }
        }
    }
}

task sourcesJar(type: Jar) {
    from android.sourceSets.main.java.srcDirs
    classifier = 'sources'
}

task javadoc(type: Javadoc) {
    source = android.sourceSets.main.java.srcDirs
    classpath += project.files(android.getBootClasspath().join(File.pathSeparator))
}

task javadocJar(type: Jar, dependsOn: javadoc) {
    classifier = 'javadoc'
    from javadoc.destinationDir
}
artifacts {
    archives javadocJar
    archives sourcesJar
}

Properties properties = new Properties()
properties.load(project.rootProject.file('local.properties').newDataInputStream())

// https://github.com/bintray/gradle-bintray-plugin
bintray {
    user = properties.getProperty("bintray.user")
    key = properties.getProperty("bintray.apikey")

    configurations = ['archives']
    pkg {
        repo = "maven"
        // it is the name that appears in bintray when logged
        name = "ffmpeg-android"
        websiteUrl = POM_URL
        vcsUrl = POM_SCM_URL
        licenses = ["GPL-3.0"]
        publish = true
        version {
            gpg {
                sign = true
                passphrase = properties.getProperty("bintray.gpg.password")
            }
            mavenCentralSync {
                sync = true
                user = properties.getProperty("bintray.oss.user") //OSS user token
                password = properties.getProperty("bintray.oss.password") //OSS user password
                close = '1'
            }
        }
    }
}

**Comment by wang-bin** [comment]
avdevice is disabled in lite build. you should remove libavdevice.so in your project

**Comment by mdemarco1234** [comment]
Hi, 

I appreciate you responding. I am not sure I understand. I was using Writing Minds project then added your binaries to replace theirs thinking that may work. Do you have an Android project I can download that compiles in Android Studio already that I can use with a minimum FFmpeg version 4.0. I need the android_camera functionality that I was told was in version 4.0 and it has to stream the camera input

**Comment by wang-bin** [comment]
too many errors to build libavdevice, for example v4l2 and fbdev, they can not be disabled by configure. I need to modify ffmpeg source code.

**Comment by wang-bin** [comment]
try the latest avbuild and run `./avbuild.sh android24`. api level 24 is required by camera, while my ci build only build the minimal api level supported by ndk, so you have to build yourself.
