### ISSUE TITLE
Is there whole ffmpeg executable file without so files ?

### ISSUE THREAD

**Issue by suncj518** [wang-bin/avbuild#17]
Is there whole ffmpeg executable file without so files ?  it is around 20M.
BTW, how to use the small ffmpeg excecubale in downloaded package? it needs .so lib files ?

**Comment by wang-bin** [comment]
ffmpeg executable in the package depends on so files. You can set environment var `LD_LIBRARY_PATH` before executing ffmpeg. for example
```
adb push ffmpeg_files /sdcard
adb shell
run-as a_debuggable_app
cp /sdcard/ffmpeg_files .
chmod +x ffmpeg_files
export LD_LIBRARY_PATH=$PWD # assume ffmpeg, lib*.so is in current dir
./ffmpeg
```

**Comment by suncj518** [comment]
Thank you.
In Android app, just put the ffmpeg bin into asset diretory,   .so files into lib directory ?

**Comment by wang-bin** [comment]
I guess yes.
