### ISSUE TITLE
windows-desktop的静态库不能用了

### ISSUE THREAD

**Issue by wangwenx190** [wang-bin/avbuild#18]
今年五六月份我曾经用过您编译的静态库，能完美使用，但最新的不行了。

最近您更新的静态库，突然就需要libmfx了，而且不链接这个库会报错，必须要链接它，但我明确记得以前是不用链接这个库的。

我使用的是您上传的[libmfx](https://sourceforge.net/projects/avbuild/files/dep/libmfx.7z/download)，Qt是我自己编译的静态版，QtAV和自带的examples都能编译成功，但都无法正常运行，打开是能打开，但只要播放媒体文件就会立即崩溃。无法上传日志，因为来不及写入日志，程序就崩了，日志文件都是空的。我曾经试过英特尔官网的libmfx，也能正常编译，但同样会崩掉。

我感觉应该不是Qt配置的问题，我编译时用的都是默认的配置，opengl 是 dynamic，VC运行时是 -MD。而且编译其他程序都没问题，运行也都很正常。难道与VS版本有关？我用的是最新版的VS2017（目前是15.8.8），但VS2017已经更新好几次了，每次重新编译的程序都会崩掉，感觉跟VS版本也没多大关系。

CONFIG += static_ffmpeg 我加上了，而且看编译后的二进制文件大小，ffmpeg应该是链接进去了的，这个没什么问题，就是程序总是会崩掉。

**Comment by wang-bin** [comment]
ffmpeg和libmfx都没问题。你看下log，不用输出到文件

**Comment by wangwenx190** [comment]
我重新编译了debug版Qt（静态库），debug版QtAV（静态库）和debug版的libmfx（源码是我自己从英特尔官网下的），用QtCreator调试了一下，发现是QtAV的问题。

下面这一段代码会报“……access violation……”的错误，我注释掉之后重新编译了QtAV，这个地方就不报错了。
```cpp
// 文件：widgets/global.cpp: 84~86行
#if !defined(QT_NO_DEBUG)
    qDebug("registerRenderers...........");
#endif
```

而下面这一段代码也会报“……access violation……”之类的错误，但我对FFmpeg不熟悉，就不知道怎么改了。
```cpp
// 文件：src/AVDemuxer.cpp: 825行
ret = avformat_find_stream_info(d->format_ctx, NULL);
```
测试项目是我自己的项目 https://github.com/wangwenx190/dynamic-desktop ，用到了您的QtAV，播放媒体文件那部分的代码是根据您给的例子写的，大概不是我这边写出了bug。

您有亲自测试过静态版的FFmpeg吗？您能检查一下是哪里的问题吗？麻烦您了。

![01](https://user-images.githubusercontent.com/17877450/47962141-358adb00-e053-11e8-937d-43908fd83392.png)

**Comment by wang-bin** [comment]
测过没问题，不过不是qtav测的
