### ISSUE TITLE
FFmpeg changed the version.sh script to ffbuild sub dir

### ISSUE THREAD

**Issue by xuguangxiao** [wang-bin/avbuild#21]
FFmpeg moved version.sh to ffbuild sub dir in version 4.1, the avbuild.sh script will not run correctly when excute under mac osx. To solve this, change the script to following will work:

`` cd $FFSRC``
``if [ -e `version.sh` ];``
``then``
``  FFVERSION_FULL=`./ffbuild/version.sh` ``
``  FFMAJOR=`./ffbuild/version.sh |sed 's,[a-zA-Z]*\([0-9]*\)\..*,\1,'` ``
``  FFMINOR=`./ffbuild/version.sh |sed 's,[a-zA-Z]*[0-9]*\.\([0-9]*\).*,\1,'` ``
``else``
``  FFVERSION_FULL=`./version.sh` ``
``  FFMAJOR=`./version.sh |sed 's,[a-zA-Z]*\([0-9]*\)\..*,\1,'` ``
``  FFMINOR=`./version.sh |sed 's,[a-zA-Z]*[0-9]*\.\([0-9]*\).*,\1,'` ``
``fi``
``FFGIT=false``

**Comment by wang-bin** [comment]
are you using master branch? it was supported for a long time

**Comment by xuguangxiao** [comment]
The build script avbuild.sh I used was from QtAV repo. I just compared two avbuild.sh, they are different. I didn't use the script from here. Maybe need sync?

**Comment by wang-bin** [comment]
yes. use this repo
