### ISSUE TITLE
想问下这个脚本适合ndk r19吗

### ISSUE THREAD

**Issue by TpOut** [wang-bin/avbuild#22]
遇到报错
/bin/sh: error while loading shared libraries: libc.so.6: cannot open shared object file: Error 24  
应该是找不到库，我的环境就配置了俩：

export FFSRC=../ffmpeg-4.1
export ANDROID_NDK=../android-ndk-r19
./avbuild.sh android "armv7"

**Comment by wang-bin** [comment]
可以，r19没有gcc，要用clang编译

    USE_TOOLCHAIN=clang ./avbuild.sh android armv7

编译日志：https://travis-ci.org/wang-bin/avbuild/jobs/484621425
