### ISSUE TITLE
arm-linux-androideabi-gcc: not found

### ISSUE THREAD

**Issue by maxest** [wang-bin/avbuild#24]
I downloaded fresh FFmpeg and placed it in avbuild folder.
I downloaded fresh Android NDK for linux and set ANDROID_NDK env var.

Shortly after I call:
./avbuild.sh android "armv7"

I get this error:
/home/maxest/Desktop/avbuild-master/ffmpeg/configure: 952: /home/maxest/Desktop/avbuild-master/ffmpeg/configure: arm-linux-androideabi-gcc: not found
C compiler test failed.

**Comment by maxest** [comment]
It helped to use clang:
./avbuild.sh android "armv7-clang"

**Comment by wang-bin** [comment]
will use clang default if gcc is no found
