### ISSUE TITLE
Android SSL problem

### ISSUE THREAD

**Issue by ismailGz** [wang-bin/avbuild#30]
Hi and thanks for this project.
When I called https urls, I get SSL errors. How can I build ffmpeg for android with SSL support?

**Comment by wang-bin** [comment]
You have to build openssh for android and enable openssh for ffmpeg

**Comment by ismailGz** [comment]
Should I change any code in avbuild scripts?

**Comment by wang-bin** [comment]
no. just add environment var "USER_OPT=--enable-openssl"

**Comment by caspermeijn** [comment]
Sorry to hijack this thread. I used "USER_OPT=--enable-openssl", but how do I tell it where to find the libraries. I got `fatal error: 'openssl/ssl.h' file not found` and I have it installed in `/opt/kdeandroid-deps/include/openssl/ssl.h`.

**Comment by wang-bin** [comment]
```
export CPATH=/opt/kdeandroid-deps/include
export LIBRARY_PATH=/opt/kdeandroid-deps/lib
```
then run avbuild.sh @caspermeijn

**Comment by caspermeijn** [comment]
@wang-bin That didn't work for me, I appear to be stumbled into a openssl error. I don't think it is avbuild related, but if you are interested take a look at this [Dockerfile and build output](https://gist.github.com/caspermeijn/2f10c2c5161d4872c720286847175804). Thanks!

**Comment by wang-bin** [comment]
I don't know. You can try to find out how to build ffmpeg openssl test code
```
   #include <openssl/ssl.h>
   #include <stdint.h>
   long check_SSL_library_init(void) { return (long) SSL_library_init; }
   int main(void) { int ret = 0;
    ret |= ((intptr_t)check_SSL_library_init) & 0xFFFF;
   return ret; }
```

**Comment by wang-bin** [comment]
supported in the latest master branch build
