### ISSUE TITLE
pkg-config uses wrong prefix

### ISSUE THREAD

**Issue by caspermeijn** [wang-bin/avbuild#31]
Hi, thanks for the great build scripts.
I use avbuild to build ffmpeg for android. I want to use pkgconfig to find the libraries, however the pkgconfig files use `/usr/local` as the prefix instead of the actual path where the libraries are installed. 
I can fix it by running the following command, but I would prefer it to be fixed upstream :-)
`sed -i 's#/usr/local#/home/user/avbuild/sdk-android-armv7-clang#g' /home/user/avbuild/sdk-android-armv7-clang/lib/pkgconfig/*`

**Comment by wang-bin** [comment]
What about change the first 4 lines to
```
prefix=${pcfiledir}/../..
exec_prefix=${prefix}
libdir=${prefix}/lib
includedir=${prefix}/include
```

**Comment by wang-bin** [comment]
try the latest code

**Comment by caspermeijn** [comment]
Thanks, this fix it for me!
