### ISSUE TITLE
Build failed under macos Mojave

### ISSUE THREAD

**Issue by Volcanoscar** [wang-bin/avbuild#33]
grep: /source.properties: No such file or directory
grep: /source.properties: No such file or directory
./avbuild.sh: line 777: [: -gt: unary operator expected
grep: /source.properties: No such file or directory
./avbuild.sh: line 777: [: -gt: unary operator expected
./avbuild.sh: line 777: [: -gt: unary operator expected
find: /toolchains/llvm/prebuilt: No such file or directory
g++: , clang++:  IS_CLANG:true, ld_lld: , as:
find: /toolchains/llvm/prebuilt: No such file or directory
find: /toolchains/llvm/prebuilt: No such file or directory
g++: , clang++:  IS_CLANG:true, ld_lld: , as:
g++: , clang++:  IS_CLANG:true, ld_lld: , as:
./avbuild.sh: line 226: -print-prog-name=lld: command not found
./avbuild.sh: line 228: -flavor: command not found
./avbuild.sh: line 230: -print-prog-name=ld.lld: command not found
./avbuild.sh: line 231: -flavor: command not found
compiler is clang: true, apple clang: false, cl: false, have lld: false
ANDROID_GCC_DIR=
ANDROID_LLVM_DIR=
./avbuild.sh: line 226: -print-prog-name=lld: command not found
./avbuild.sh: line 226: -print-prog-name=lld: command not found
./avbuild.sh: line 228: -flavor: command not found
./avbuild.sh: line 228: -flavor: command not found
./avbuild.sh: line 230: -print-prog-name=ld.lld: command not found
./avbuild.sh: line 230: -print-prog-name=ld.lld: command not found
./avbuild.sh: line 231: -flavor: command not found
./avbuild.sh: line 231: -flavor: command not found

**Comment by wang-bin** [comment]
more details please. build command? for android? ndk version?

**Comment by Volcanoscar** [comment]
build command :  ./avbuild.sh android21 "armv7-clang arm64"
 ndk version : r15c

**Comment by wang-bin** [comment]
did you forget to set environment var `ANDROID_NDK`?

**Comment by Volcanoscar** [comment]
Already set to r15c

**Comment by wang-bin** [comment]
> grep: /source.properties: No such file or directory
This line show your ANDROID_NDK is empty. How do you set ANDROID_NDK?

I build in WSL with r15c and no such errors.

**Comment by Volcanoscar** [comment]
I use zsh as bash backend, which I have configured ANDROID_NDK in the ~/.zshrc. When I run `echo $ANDROID_NDK`, it returns the right path of the ndk. FYI, after running `export ANDROID_NDK=/path/to/the/ndk`, it succeeded. Tks for ur help.
