### ISSUE TITLE
Unable to create mkv containers on Android using lite version

### ISSUE THREAD

**Issue by nejatafshar** [wang-bin/avbuild#34]
When using the built FFmpeg 4.2 Lite on Windows and Linux I can create mkv containers using `avformat_alloc_output_context2`. But using the built FFmpeg 4.2 Lite (armeabi-v7a) on Android, trying to create mkv containers for the same video gives me error:

`[FFmpeg:NULL] Unable to find a suitable output format for '/data/data/Sample/files/1.mkv'`

But using mp4 is fine on Android. Is this feature for mkv turned off for Android?

**Comment by wang-bin** [comment]
yes, it's disabled on mobile platforms

**Comment by nejatafshar** [comment]
@wang-bin Thanks. What's the reason for disabling it on mobile platform?

**Comment by wang-bin** [comment]
This configuration is for players. I though encoders and muxers are not useful for players. So most of them are disabled to minimize the binary size.

**Comment by nejatafshar** [comment]
@wang-bin You are right, minimizing binary size for mobile is necessary.
