### ISSUE TITLE
Win64平台仍然无法摆脱MSYS2吗?

### ISSUE THREAD

**Issue by RPG3D** [wang-bin/avbuild#36]

**Comment by wang-bin** [comment]
编译环境必须要有bash，所以要么用msys2，要么用wsl+clang。wsl里编译更快。当然也可以在其他系统上编译，linux、mac都行，用clang+windows sdk。

**Comment by RPG3D** [comment]
> 编译环境必须要有bash，所以要么用msys2，要么用wsl+clang。wsl里编译更快。当然也可以在其他系统上编译，linux、mac都行，用clang+windows sdk。

请问下里面有什么模块必须依赖于bash？如果能更加纯粹一点，比如在win64 仅依赖cmake，bat， vs之类的会方便不少

**Comment by wang-bin** [comment]
主要是configure这个文件，用于配制ffmpeg要编译的功能、不同编译工具的参数等，这个工程量很大，要改成功能差不多的cmake很有难度，最好是ffmpeg官方去维护，不然得和ffmpeg的变更同步。还有一些编译过程中用到的脚本也是bash写的。如果仅仅是支持某个目标平台，比如win64，工作量会小一点
