### ISSUE TITLE
dlopen failed: invalid ELF file android

### ISSUE THREAD

**Issue by manang** [wang-bin/avbuild#41]
Hi,
when I use the master prebuilt libraries I have the following error
dlopen failed: invalid ELF file /usr/arm64/libswscale.so.
I don't have this error with the 4.2 libraries.
I need the master because I have to compile for x86_64 for android and in 4.2 prebuilt zip there are not the x86_64 libs.
Thank you very much
Angelo

**Comment by wang-bin** [comment]
I see this error 
```
 dlopen error: dlopen failed: invalid ELF file "/data/app/android.mdk.sdk-_7fNrmDOXbxpK-48fQx_RQ==/lib/arm64/libswscale.so" load segment[4]: p_offset (0x41000) + p_filesz (0x0) ( = 0x41000) past end of file (0x40a60)
```

other ffmpeg modules are fine. I have no idea. 4.2 was built with ndk20, master is ndk21. can you try to build with ndk r20?

**Comment by manang** [comment]
I built with ndk21.
I built ffmpeg 4.2 and I have the same problem.
Can you build and share ffmpeg 4.2 for x86_64 on sourceforge?
Thank you very much

**Comment by wang-bin** [comment]
https://sourceforge.net/projects/avbuild/files/android/ffmpeg-4.2-android-lite.tar.xz/download

Try this. If this build is fine, then probably it's a ffmpeg bug

**Comment by manang** [comment]
can you tell me which differences have the lite version and the standard one?
Thanks

**Comment by manang** [comment]
I tried wit your last version, but I still have 
 java.lang.UnsatisfiedLinkError: dlopen failed: invalid ELF file "/data/app/io.fd.viper-ona0NuZvuqURUW725tsRew==/lib/arm64/libswscale.so" load segment[4]: p_offset (0x41000) + p_filesz (0x0) ( = 0x41000) past end of file (0x40a60)

**Comment by wang-bin** [comment]
I see. I tested ndk r20b, the same error. So my script is broken since Sep 2019

**Comment by wang-bin** [comment]
lite version enables less features. standard version use the default configuration.

https://github.com/wang-bin/avbuild/blob/master/config-lite.sh

**Comment by manang** [comment]
so you think that the problem is the script.
Let me check if I use an old commit.
thanks for your support

**Comment by wang-bin** [comment]
I will use `git bisect` to find out the broken commit tomorrow.

**Comment by wang-bin** [comment]
the working prebuilt package is 2019-09-13. I revert my code before that day, still wrong result. I compare the configurations, the only difference is one is built with ndk r20, another is ndk r21b. I will try ndk r20 tomorrow.

**Comment by manang** [comment]
thanks a lot!

**Comment by wang-bin** [comment]
Using llvm-strip instead of the one in gnu binutils fix the bug. Try the latest lite build of master branch. see https://github.com/android/ndk/issues/1148

**Comment by manang** [comment]
I noticed that you compiled again the version 4.2?
Thanks

**Comment by wang-bin** [comment]
master and 4.2 are all updated

**Comment by manang** [comment]
I tried to use the 4.2 prebuilt version, but I have the same error of before.
I can launch the application only if I have the master lite prebuilt version.

Thanks for your support
Angelo

**Comment by wang-bin** [comment]
Did you use ffmpeg-4.2-android-lite.tar.xz? I forgot to rebuild it. I updated this one about 1 hour ago. Please try again.

**Comment by manang** [comment]
I'm trying now.

Thanks

**Comment by manang** [comment]
I can confirm that with your last modification qtav, linked against ffmpeg 4.2 lite, works well.
Thank you very much
Anelo
