### ISSUE TITLE
要启用GuardCF，链接器也需要传一个参数

### ISSUE THREAD

**Issue by wangwenx190** [wang-bin/avbuild#44]
如果想要启用GuardCF这个特性，不仅需要给编译器传`/guard:cf`这个参数，链接器也需要传一个相同的参数`/guard:cf`，链接器缺少这个参数的话这个特性其实是没有启用的。

从下面的两幅图片也可以看出，图一是MDK自带的ffmpeg，就是用这个仓库的脚本编译的，我看了您写的脚本，发现您已经传了`-guard:cf`或`-cfguard`参数，看得出来您是想启用这个特性的，但是您没有给链接器也传这个参数，所以实际上最终得到的文件是没有启用这个特性的。

而图二是我自己用clang-cl + lld-link编译的ANGLE，从图里能看到，特性里多了`GuardCF`这个关键词，这才是真正启用了，而您自己编译的不管是MDK还是ffmpeg，都没有这个关键词，也就是都没有真正启用这个特性。

![picture1](https://user-images.githubusercontent.com/17877450/76155192-8fa61f80-6123-11ea-8343-72b7771b42aa.png)

![picture2](https://user-images.githubusercontent.com/17877450/76155194-959c0080-6123-11ea-9e83-c30d82e98db7.png)

**Comment by wang-bin** [comment]
这是怎么查看的？

**Comment by wangwenx190** [comment]
选中exe或dll文件，右键->7-Zip->打开压缩包，在弹出的7-Zip窗口里点击最右边那个【信息】按钮就行，Windows上是这样的。7-Zip是原版的，从 https://www.7-zip.org/ 这里下载的。

**Comment by wangwenx190** [comment]
估计MSVC自带的工具也能读取`DLL Characteristis`这个东西，我是碰巧在用7-Zip时发现的，就一直用这个方法查看。

**Comment by wang-bin** [comment]
llvm-readobj --coff-load-config也可以查看

**Comment by wangwenx190** [comment]
除了Windows平台，其他平台也存在这个问题吗？确实需要给链接器也传参数吗？

**Comment by wangwenx190** [comment]
> 
> 
> llvm-readobj --coff-load-config也可以查看

您这个方法更正规一些，不过在Windows上还是用7z更方便一些，毕竟鼠标点两下就能看了 :)

**Comment by wang-bin** [comment]
貌似是编译加/d2guard4 链接加/guard:cf

**Comment by wangwenx190** [comment]
我查过MSDN，`/d2guard4`是旧版的参数，新版统一都改成`/guard:cf`了，编译和链接都是这个参数

**Comment by wang-bin** [comment]
mac和linux的clang都带，不知道win为啥不带

**Comment by wangwenx190** [comment]
win平台可能有不一样的地方，您最好还是改下脚本

**Comment by wangwenx190** [comment]
https://docs.microsoft.com/zh-cn/visualstudio/releasenotes/vs2015-rtm-vs

![图片](https://user-images.githubusercontent.com/17877450/76155873-49ee5480-612d-11ea-8706-97be94d17747.png)

**Comment by wang-bin** [comment]
测了下链接传参有效

**Comment by wang-bin** [comment]
谢谢

**Comment by wang-bin** [comment]
dumpbin /loadconfig 和llvm-readobj输出内容差不多

**Comment by wangwenx190** [comment]
举手之劳而已，您客气了。
