### ISSUE TITLE
能否提供LAVFilters的动态库

### ISSUE THREAD

**Issue by YexuanXiao** [wang-bin/avbuild#47]
项目地址： https://github.com/Nevcairiel/LAVFilters ， LAVFilters 是一个基于 FFmpeg 的容器/音视频分离器，作者一直在维护但是并没有发布新的二进制文件，而已有的二进制文件使用的 ffmpeg 已经很旧了。

**Comment by wang-bin** [comment]
可以的，以前编过，我直接ci里加一条就行了

**Comment by wang-bin** [comment]
可以在sourceforge上下载l https://sourceforge.net/projects/avbuild/files/windows-desktop/ffmpeg-master-windows-desktop-clang-lavfilters.tar.xz/download

或者从github action 的artifacts下载，比如 https://github.com/wang-bin/avbuild/actions/runs/418908088#artifacts 

包名以-lavfilters结尾
