### ISSUE TITLE
android gcc如何编译？

### ISSUE THREAD

**Issue by Whu-wxy** [wang-bin/avbuild#52]
以下是输入的命令：
`export FFSRC=D:/zzxs/codes/FFmpeg-master
./avbuild.sh android "armv7-gcc"
`

sh文件中添加：
`USE_TOOLCHAIN = gcc
ANDROID_GCC_DIR=D:/UserApps/Programs/android-ndk-r10e/toolchains/arm-linux-androideabi-4.8/prebuilt/windows-x86_64/arm-linux-androideabi/bin
`

build失败，如下：
`
configuration changes
clang is unable to create an executable file.
C compiler test failed.
......
......
/d/zzxs/codes/FFmpeg-master/configure: line 984: clang: command not found
C compiler test failed.
`

创建了文件夹：build_sdk-android-armv7-clang

请问armv7-gcc如何正确编译？

**Comment by wang-bin** [comment]
设环境变量ANDROID_NDK就行然后`./avbuild.sh android armv7`。不过现在没必要用这么老的ndk和gcc了，所以没维护，不一定还能正确编译

**Comment by wang-bin** [comment]
https://github.com/wang-bin/avbuild/wiki/Android
