### ISSUE TITLE
Windows编译ffmpeg报错

### ISSUE THREAD

**Issue by tinghui-sun** [wang-bin/avbuild#54]
按以下步骤在windows平台下编译ffmpeg报错。
1. 通过msys2_shell.cmd 启动 msys2
2. cd到avbuild目录，执行./avbuild.sh mingw "x86_64"
报以下错误
configure --extra-version=QtAV --disable-doc --disable-debug --enable-shared --enable-runtime-cpudetect --disable-iconv --disable-postproc --cc=x86_64-w64-mingw32-gcc --target-os=mingw64 --enable-pic --extra-ldflags="-static-libgcc -Wl,-Bstatic" --enable-gpl --enable-nonfree --enable-version3
.env.sh: line 1: syntax error near unexpected token `('
.env.sh: line 1: `export PATH=/mingw64/bin:/mingw64/bin:/d/Code/OpenSource/ffmpeg/ffmpeg-4.2.3:/d/code/opensource/avbuild/tools/gas-preprocessor:/usr/local/bin:/usr/bin:/bin:/opt/bin:/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/HostX64/x64:/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/VC/VCPackages:/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/TestWindow:/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer:/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/MSBuild/15.0/bin/Roslyn:/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/Team Tools/Performance Tools/x64:/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/Team Tools/Performance Tools:/c/Program Files (x86)/Microsoft Visual Studio/Shared/Common/VSPerfCollectionTools/x64:/c/Program Files (x86)/Microsoft Visual Studio/Shared/Common/VSPerfCollectionTools:/c/Program Files (x86)/Microsoft SDKs/Windows/v10.0A/bin/NETFX 4.6.1 Tools/x64:/c/Program Files (x86)/HTML Help Workshop:/c/Program Files (x86)/Windows Kits/10/bin/10.0.17763.0/x64:/c/Program Files (x86)/Windows Kits/10/bin/x64:/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/MSBuild/15.0/bin:/c/Windows/Microsoft.NET/Framework64/v4.0.30319:/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE:/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/Tools:/c/Python39/Scripts:/c/Python39:/c/Program Files (x86)/IntelSWTools/Intel(R) Media SDK 2020 R1/Software Development Kit/bin/x64:/c/Program Files (x86)/IntelSWTools/Intel(R) Media SDK 2020 R1/Software Development Kit/bin/win32:/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.1/bin:/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.1/libnvvp:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Windows/System32/OpenSSH:/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/c/Program Files/CMake/bin:/c/Program Files/Git/cmd:/c/Program Files/TortoiseGit/bin:/c/Program Files/dotnet:/d/gstreamer/1.0/msvc_x86_64/bin:/c/Program Files/NVIDIA Corporation/NVSMI:/c/Program Files/NVIDIA Corporation/Nsight Compute 2020.2.0:/c/ProgramData/chocolatey/bin:/c/Program Files (x86)/nodejs:/c/Program Files/TortoiseSVN/bin:/c/Users/25218/AppData/Local/Microsoft/WindowsApps:/d/gstreamer/1.0/msvc_x86_64/bin:/c/Users/25218/AppData/Local/Programs/Microsoft VS Code/bin:/c/Program Files/JetBrains/PyCharm Community Edition 2021.1.1/bin:/c/Users/25218/AppData/Roaming/npm:/c/Program Files (x86)/Windows Kits/10/bin/x64:/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin:/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl'
configuration changes
Out of tree builds are impossible with config.h in source dir.

**Comment by tinghui-sun** [comment]
修改msys2_shell.cmdm, rem set MSYS2_PATH_TYPE=inherit 屏蔽PATH_TYPE参数后，
执行./avbuild.sh mingw "x86_64"，上面的错误消失了，但报另外一个错误
make: lib.exe: No such file or directory

而想用lib.exe的话， 又需要打开MSYS2_PATH_TYPE=inherit配置项。

Help!!!

**Comment by wang-bin** [comment]
不需要lib.exe。mingw相关的编译工具装好了没？另外你的ffmpeg代码目录不干净，没法编译
