### ISSUE TITLE
/opt/vc/lib/libopenmaxil.so not found

### ISSUE THREAD

**Issue by wwtssu** [wang-bin/avbuild#57]
在树莓派4b直接运行avbuild.sh host编译n4.4.1完成后
cd build_sdk-rpi-armv6-gcc
sudo make install
sudo ldconfig
然后使用-c:v h264_omx出现
[h264_omx @ 0xb841d0] /opt/vc/lib/libopenmaxil.so not found
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!
是有什么我没有处理的吗？

**Comment by wwtssu** [comment]
ls /opt/vc/lib/
libbcm_host.so         libelftoolchain.so     libopenmaxil.so
libbrcmEGL.so          libGLESv1_CM.so        libOpenVG.so
libbrcmGLESv2.so       libGLESv2.so           libvchiq_arm.so
libbrcmOpenVG.so       libGLESv2_static.a     libvchostif.a
libbrcmWFC.so          libkhrn_client.a       libvcilcs.a
libcontainers.so       libkhrn_static.a       libvcos.so
libdebug_sym.so        libmmal_components.so  libvcsm.so
libdebug_sym_static.a  libmmal_core.so        libWFC.so
libdtovl.so            libmmal.so             pkgconfig
libEGL.so              libmmal_util.so        plugins
libEGL_static.a        libmmal_vc_client.so
文件是有的

**Comment by wang-bin** [comment]
4b好像不支持omx，而且以后的系统会移除omx。你可以运行 lld -r /opt/vc/lib/libopenmaxil.so 看下有什么符号找不到。现在推荐使用h264_v4l2m2m，用常规的linux目标编译就行 https://sourceforge.net/projects/avbuild/files/linux/ffmpeg-master-linux-clang-lite.tar.xz/download
