### ISSUE TITLE
Consider adding ProRes encoder to the builds

### ISSUE THREAD

**Issue by AdrianEddy** [wang-bin/avbuild#58]
It would be nice to have `prores_ks` codec enabled, currently I have to use the full ffmpeg version which is much larger for just this one codec.

**Comment by wang-bin** [comment]
what's the difference of prores and prores_ks?

**Comment by AdrianEddy** [comment]
Looks like there are 3 versions of prores encoders, but everywhere I seen, `prores_ks` is the recommended one and it's the one I use and works fine. More information is here: https://trac.ffmpeg.org/wiki/Encode/VFX#:~:text=Prores%20is%20a,version%20of%20prores.

**Comment by wang-bin** [comment]
the latest master branch build enables prores encoders

**Comment by AdrianEddy** [comment]
thank you!
