### ISSUE TITLE
[Windows] 建议给dll添加版本信息

### ISSUE THREAD

**Issue by wangwenx190** [wang-bin/avbuild#59]
我记得很早的时候dll是有版本信息的（也可能是我记错了），总之现在的dll都完全没有版本信息（属性页那个），能添加一下吗？

**Comment by wang-bin** [comment]
好像一直没有，lite版本的--enable-small会导致rc不被编译，rc编译又需要gnu的windres，这东西llvm不一定带，msvc更没有了。我得确认下编译ci环境有没有带windres，然后改下configure文件

**Comment by wang-bin** [comment]
clang交叉编译差不多搞定了。windows的llvm竟然不带windres，mingw的windres太弱了只支持x86目标，这个就有点麻烦了，感觉还得自己编译一个windres

**Comment by wang-bin** [comment]
windres原来其实就是llvm-rc

**Comment by wangwenx190** [comment]
自己编译windres有点麻烦吧，不能把二进制打包进deps里到时候直接拿来用吗

**Comment by wang-bin** [comment]
不用编译，拷贝一份llvm-rc为llvm-windres就行

**Comment by wang-bin** [comment]
master的包已经有了

**Comment by wangwenx190** [comment]
给力，感谢老大！
👍
