### ISSUE TITLE
关于版本的不同

### ISSUE THREAD

**Issue by zero16832** [wang-bin/avbuild#66]
能不能讲一下 那几个后续 default lto lite 这几个版本的区别丫？

**Comment by wang-bin** [comment]
default: configure默认配置，没什么增减功能

lite: 只保留一些常用的功能，并且优化二进制大小。可以看config-lite.sh

ltl: 使用静态crt，链接到vc-ltl5，二进制不依赖ucrt

**Comment by zero16832** [comment]
default 有没有开硬件加速的丫？我调用 h264_mediacodec 发现提示 虚拟机没创建？

**Comment by wang-bin** [comment]
所有版本都开硬件加速了

**Comment by zero16832** [comment]
我看到 avbuild.sh #: ${FEATURE_OPT:="--enable-hwaccels"} 这里注释了？

**Comment by zero16832** [comment]
感谢大佬帮助，最后我想问一下，我想编译后的dll 不带版本信息 我该修改哪里呢？比如-60 我不想要生成的DLL 文件 带这个

**Comment by wang-bin** [comment]
不能也没必要，不同的版本号不兼容，正常的库都这么做的。真要用的话用ffmpeg-*.dll改个名

**Comment by zero16832** [comment]
主要 我想用来做跨平台，我发现直接改名字 之后[dllimport]不支持了 现在 安卓的不带版本号，WIN 的带版本号，通过ffmpeg.gen 生成出来的接口文件不通用

**Comment by wang-bin** [comment]
只有android的库是都不带版本号的，所有其他系统都有版本号，ffmpeg生产的库也按各系统的习惯来的

**Comment by zero16832** [comment]
好的，感谢大佬帮助。
