### ISSUE TITLE
关于IOS

### ISSUE THREAD

**Issue by zero16832** [wang-bin/avbuild#68]
突然发现 IOS 的包 都没有ffmpeg.a的？这是为啥呢？

**Comment by zero16832** [comment]
而且 ios 没有default包了

**Comment by wang-bin** [comment]
静态库可以用户自己合并，但是动态库不行，所以提供了动态库。使用合并后的静态库只是链接参数减少了，生成的二进制文件运行时依赖不变，和使用多个静态库效果没区别

**Comment by wang-bin** [comment]
最新包里加了libffmpeg.a，不过不是静态库，链接会比较快
