### ISSUE TITLE
Windows Defender detect ffmpeg.exe as torjan

### ISSUE THREAD

**Issue by thewh1teagle** [wang-bin/avbuild#70]
I use `avbuild` in the project [vibe](https://github.com/thewh1teagle/vibe) and recently people reported that windows defender block the program with the error:

```console
The file C:\Users\User\AppData\Local\vibe\ffmpeg.exe is infected with Gen:Variant.Lazy.540663 and was moved to quarantine. It is recommended that you run a System Scan to make sure your system is clean.
```
The file is [ffmpeg-6.1-windows-desktop-vs2022ltl-default.7z](https://master.dl.sourceforge.net/project/avbuild/windows-desktop/ffmpeg-6.1-windows-desktop-vs2022ltl-default.7z?viasf=1)

It's probably false positive by Windows defender, I reported to Microsoft that it's false positive at [wdsi/filesubmission](https://www.microsoft.com/en-us/wdsi/filesubmission?persona=SoftwareDeveloper)
Hope you can solve it
Thanks!

Related: https://github.com/thewh1teagle/vibe/issues/126

Also virus total:
https://www.virustotal.com/gui/file/c91b4c9b8e5220ec5e511863a652aefb8ea08deae0bb80fb7466c4f65a09dfad

**Comment by wang-bin** [comment]
i can't fix it. don't use ltl, use vs2022 instead.

**Comment by thewh1teagle** [comment]
> i can't fix it. don't use ltl, use vs2022 instead.

This one? [avbuild/files/windows-desktop/ffmpeg-7.0-windows-desktop-vs2022-default.7z](https://sourceforge.net/projects/avbuild/files/windows-desktop/ffmpeg-7.0-windows-desktop-vs2022-default.7z/download)

What's the differences between all the builds? (`lgpl`, `lite`, etc) did you wrote the differences in some place?

**Comment by wang-bin** [comment]
yes. default: default features. lite: only some frequently used features and optimized for binary size. gpl: add some features in gpl license, for example x264 x265. ltl: build with vc-ltl to link to mscvrt instead of ucrt

**Comment by wang-bin** [comment]
vc-ltl author says the reason is linking to msvcrt, we can do nothing. so recommand to use ucrt.

**Comment by wang-bin** [comment]
i have no idea about virus

**Comment by thewh1teagle** [comment]
> i have no idea about virus, afaik only ltl build is detected as virus. you can also try the binaries build by someone else

It happens also with  [ffmpeg-7.0-windows-desktop-vs2022-default.7z](https://unlimited.dl.sourceforge.net/project/avbuild/windows-desktop/ffmpeg-7.0-windows-desktop-vs2022-default.7z?viasf=1) (detected by MaxSecure in virustotal) see [virustotal.com/gui/file/40cc](https://www.virustotal.com/gui/file/40cc5a8d44dbf4b20375ab4629324c45fda2b1cba7bdf48dbbbc4e560b03ea32)

**Comment by wang-bin** [comment]
No virus detectd: https://www.virustotal.com/gui/url/e679ce80f7c2e6ee0322a3275bf3e10e2dab41a60acc545a455add8a41ea3bc0?nocache=1

You can test the binaries from https://ffmpeg.org/download.html
