### ISSUE TITLE
Can't run avbuild on forked github repo

### ISSUE THREAD

**Issue by Predidit** [wang-bin/avbuild#71]
My fork is here

https://github.com/Predidit/avbuild

Is this related to github actions caching? I noticed that the official repository's github actions have some long-term caches, but obviously, I don't have those caches.

**Comment by wang-bin** [comment]
需要配置些变量，就是yml里的${{ vars.xxx }}，其中FF_VER是master或版本号如7.0 6.1，LLVM_VER我设了19。有些jobs你可以删掉，比如上传到sourceforge。现在github打不开，没法截图给你看我的设置，你先自己研究下

**Comment by wang-bin** [comment]
<img width="1063" alt="image" src="https://github.com/user-attachments/assets/d41b62f8-94ea-4648-978e-afc6336b2d11">
LINUX_SYSROOT_ID随便填，是为了更新缓存用的

**Comment by wang-bin** [comment]
https://github.com/zero16832/avbuild/actions/runs/8524011959 这是别人fork后的构建

**Comment by Predidit** [comment]
非常感谢您的帮助

我编译出了移除 gif 格式支持的 ffmpeg 库
