### ISSUE TITLE
编译最新的ffmpeg7.1,无法生成单一的ffmpeg.dll

### ISSUE THREAD

**Issue by ArtistZhou** [wang-bin/avbuild#72]
mklibffmpeg.sh是不是该更新了，报了一堆重定义错误
s_rc.o : error LNK2005: ff_opus_rc_enc_uint_tri 已经在 rc.o 中定义
opus_rc.o : error LNK2005: ff_opus_rc_get_raw 已经在 rc.o 中定义
opus_rc.o : error LNK2005: ff_opus_rc_put_raw 已经在 rc.o 中定义
opus_silk.o : error LNK2005: ff_silk_decode_superframe 已经在 silk.o 中定义
opus_silk.o : error LNK2005: ff_silk_flush 已经在 silk.o 中定义
opus_silk.o : error LNK2005: ff_silk_free 已经在 silk.o 中定义
opus_silk.o : error LNK2005: ff_silk_init 已经在 silk.o 中定义
packet.o : error LNK2005: av_grow_packet 已经在 avpacket.o 中定义
packet.o : error LNK2005: av_init_packet 已经在 avpacket.o 中定义
packet.o : error LNK2005: av_new_packet 已经在 avpacket.o 中定义

**Comment by wang-bin** [comment]
default or lite?

**Comment by wang-bin** [comment]
[github actions](https://github.com/wang-bin/avbuild/actions/runs/11197418855)上和我本地编译都没问题，而且不存在s_rc.o、opus_rc.o、opus_silk.o、avpacket.o 这些文件，你的环境有问题
