### ISSUE TITLE
Any plan for ffprobe support?

### ISSUE THREAD

**Issue by mgenware** [wang-bin/avbuild#74]

**Comment by wang-bin** [comment]
why do you think it's not supported?

**Comment by mgenware** [comment]
Hi @wang-bin ,

> why do you think it's not supported?

Because I downloaded iOS binaries, both .a and xcframeworks. They are all named `ffmpeg` not `ffprobe`. Are you suggesting that ffprobe is somehow glued into those downloaded ffmpeg binaries? Or should we build manually for ffprobe? Would you mind provding more info for future readers? Thanks!

**Comment by wang-bin** [comment]
it's impossible to execute ffprobe or ffmpeg(and any command line executables) on iOS. you have to build them as a standard iOS app.
