### ISSUE TITLE
请问如何传递自定义参数编译ffmpeg

### ISSUE THREAD

**Issue by duiniuluantanqin** [wang-bin/avbuild#75]
比如我的编译参数为
```
--enable-libfreetype \
--enable-libharfbuzz \
--enable-libx264 \
--enable-libx265 \
--enable-mediafoundation \
--enable-dxva2 \
--enable-d3d11va \
--enable-d3d12va
```
如何传递给`avbuild.sh`

**Comment by wang-bin** [comment]
把config-lite.sh重命名为config.sh，按需修改里面的内容。dxva2, d3d11va, d3d12va是自动检测并启用的，不用自己enable。x264/5我在config-gpl-lite.sh里启用了，freetype、harfbuzz也有计划加到gpl版本里去

**Comment by wang-bin** [comment]
gpl包带了x2645， 最新的gpl包包含了freetype harfbuzz，用于drawtext filter。
